name: Deploy to Nexus repository
on:
    workflow_dispatch:
    workflow_run:
        workflows: [ "Build" ]
        branches: [ main ]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Run build with Gradle Wrapper
              run: ./gradlew publish
              env:
                  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}