name: Deploy to Nexus repository
on:
    workflow_run:
        workflows: [ "Build" ]
        branches: [ main ]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ 8 ]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
            - name: Publish
              run: gradle publish
              env:
                  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}